server:
  port: 58080

spring:
  application:
    name: cloud-sleuth-zipkin-grpc-server
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1
grpc:
  server:
    port: 0
