#datasource:
#  master:
#    url: jdbc:mysql://127.0.0.1:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    driver: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
spring:
  redis:
    host: 127.0.0.1
    database: 1
    port: 6379
