#datasource:
#  master:
#    url: jdbc:mysql://192.168.9.208:3306/oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    driver: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
spring:
  redis:
    host: 192.168.9.234
    database: 1
    port: 6379
