{
 "title": "Microservices (gRPC) Monitoring",
 "description": "Microservices(gRPC) dashboard with Prometheus data source. It supports the metrics defined in https://github.com/grpc/proposal/blob/master/A66-otel-stats.md",
 "time": { "from": "now-3d", "to": "now" },
 "panels": [
  { "title": "Client Side Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client RPC Attempts Started",
   "type": "timeseries",
   "description": "The total number of RPC attempts started on the client side per second, including those that have not completed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_attempt_started_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client RPC Attempt Duration (second)",
   "type": "timeseries",
   "description": "End-to-end time taken to complete an RPC attempt including the time it takes to pick a subchannel.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.5,\n    sum by (le) (rate(grpc_client_attempt_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum by (le) (rate(grpc_client_attempt_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum by (le) (rate(grpc_client_attempt_duration_seconds_bucket[$__rate_interval]))\n)",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sum(rate(grpc_client_attempt_duration_seconds_sum[$__rate_interval]))/sum(rate(grpc_client_attempt_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Client Sent Compressed Message Bytes per second",
   "type": "timeseries",
   "description": "Total bytes (compressed but not encrypted) sent across all request messages (metadata excluded) per second; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_client_attempt_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_client_attempt_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_client_attempt_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sum(rate(grpc_client_attempt_sent_total_compressed_message_size_bytes_sum[$__rate_interval]))/sum(rate(grpc_client_attempt_sent_total_compressed_message_size_bytes_count[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Client Sent Compressed Message Bytes per RPC Attempt",
   "type": "heatmap",
   "description": "Total bytes (compressed but not encrypted) sent across all request messages (metadata excluded) per RPC attempt; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_attempt_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Received Compressed Message Bytes per second",
   "type": "timeseries",
   "description": "Total bytes (compressed but not encrypted) received across all response messages (metadata excluded) per second; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_client_attempt_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_client_attempt_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_client_attempt_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sum(rate(grpc_client_attempt_rcvd_total_compressed_message_size_bytes_sum[$__rate_interval]))/sum(rate(grpc_client_attempt_rcvd_total_compressed_message_size_bytes_count[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Client Received Compressed Message Bytes per RPC Attempt",
   "type": "heatmap",
   "description": "Total bytes (compressed but not encrypted) received across all response messages (metadata excluded) per RPC attempt; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_attempt_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server Side Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Server Call Started",
   "type": "timeseries",
   "description": "The total number of RPC calls started on the server side per second, including those that have not completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_call_started_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server RPC Duration (second)",
   "type": "timeseries",
   "description": "This metric aims to measure the end2end time an RPC takes from the server transport’s (HTTP2/ inproc) perspective.\nStart timestamp - After the transport knows that it's got a new stream. For HTTP2, this would be after the first header frame for the stream has been received and decoded. Whether the timestamp is recorded before or after HPACK is left to the implementation.\nEnd timestamp - Ends at the first point where the transport considers the stream done. For HTTP2, this would be when scheduling a trailing header with END_STREAM to be written, or RST_STREAM, or a connection abort. Note that this wouldn’t necessarily mean that the bytes have also been immediately scheduled to be written by TCP.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_server_call_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_call_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_call_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sum(rate(grpc_server_call_duration_seconds_sum[$__rate_interval]))/sum(rate(grpc_server_call_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Server Sent Compressed Message Bytes per second",
   "type": "timeseries",
   "description": "Total bytes (compressed but not encrypted) sent across all response messages (metadata excluded) per second; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_server_call_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_call_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_call_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sum(rate(grpc_server_call_sent_total_compressed_message_size_bytes_sum[$__rate_interval]))/sum(rate(grpc_server_call_sent_total_compressed_message_size_bytes_count[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Server Sent Compressed Message Bytes per RPC",
   "type": "heatmap",
   "description": "Total bytes (compressed but not encrypted) sent across all response messages (metadata excluded) per RPC; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_call_sent_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Received Compressed Message Bytes per second",
   "type": "timeseries",
   "description": "Total bytes (compressed but not encrypted) received across all request messages (metadata excluded) per second; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50 percentile"
    },
    {
     "expr": "histogram_quantile(0.95,sum(rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99 percentile"
    },
    {
     "expr": "sum(rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_sum[$__rate_interval]))/sum(rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_count[$__rate_interval]))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Server Received Compressed Message Bytes per RPC",
   "type": "heatmap",
   "description": "Total bytes (compressed but not encrypted) received across all request messages (metadata excluded) per RPC; does not include grpc or transport framing bytes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_call_rcvd_total_compressed_message_size_bytes_bucket[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}