// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay-api.proto

package my.suveng.istio.grpc.api.pay;

public final class Pay {
  private Pay() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PayRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PayRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PayResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PayResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rpay-api.proto\"\033\n\nPayRequest\022\r\n\005money\030\001" +
      " \001(\t\"\036\n\013PayResponse\022\017\n\007success\030\002 \001(\0102\377\001\n" +
      "\nPayService\0222\n\025getRealNameByUsername\022\013.P" +
      "ayRequest\032\014.PayResponse\022=\n\036getRealNameBy" +
      "UsernameResStream\022\013.PayRequest\032\014.PayResp" +
      "onse0\001\022=\n\036getRealNameByUsernameReqStream" +
      "\022\013.PayRequest\032\014.PayResponse(\001\022?\n\036getReal" +
      "NameByUsernameStreamAll\022\013.PayRequest\032\014.P" +
      "ayResponse(\0010\001B%\n\034my.suveng.istio.grpc.a" +
      "pi.payB\003PayP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PayRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PayRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PayRequest_descriptor,
        new java.lang.String[] { "Money", });
    internal_static_PayResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PayResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PayResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
