// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay-api.proto

package my.suveng.istio.grpc.api.pay;

public interface PayRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PayRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string money = 1;</code>
   * @return The money.
   */
  java.lang.String getMoney();
  /**
   * <code>string money = 1;</code>
   * @return The bytes for money.
   */
  com.google.protobuf.ByteString
      getMoneyBytes();
}
