// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay-api.proto

package my.suveng.istio.grpc.api.pay;

public interface PayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();
}
