// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pay-api.proto

package my.suveng.istio.grpc.api.pay;

/**
 * Protobuf type {@code PayRequest}
 */
public final class PayRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PayRequest)
    PayRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PayRequest.newBuilder() to construct.
  private PayRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PayRequest() {
    money_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PayRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PayRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            money_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return my.suveng.istio.grpc.api.pay.Pay.internal_static_PayRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return my.suveng.istio.grpc.api.pay.Pay.internal_static_PayRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            my.suveng.istio.grpc.api.pay.PayRequest.class, my.suveng.istio.grpc.api.pay.PayRequest.Builder.class);
  }

  public static final int MONEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object money_;
  /**
   * <code>string money = 1;</code>
   * @return The money.
   */
  @java.lang.Override
  public java.lang.String getMoney() {
    java.lang.Object ref = money_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      money_ = s;
      return s;
    }
  }
  /**
   * <code>string money = 1;</code>
   * @return The bytes for money.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMoneyBytes() {
    java.lang.Object ref = money_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      money_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMoneyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, money_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMoneyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, money_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof my.suveng.istio.grpc.api.pay.PayRequest)) {
      return super.equals(obj);
    }
    my.suveng.istio.grpc.api.pay.PayRequest other = (my.suveng.istio.grpc.api.pay.PayRequest) obj;

    if (!getMoney()
        .equals(other.getMoney())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONEY_FIELD_NUMBER;
    hash = (53 * hash) + getMoney().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static my.suveng.istio.grpc.api.pay.PayRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(my.suveng.istio.grpc.api.pay.PayRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PayRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PayRequest)
      my.suveng.istio.grpc.api.pay.PayRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return my.suveng.istio.grpc.api.pay.Pay.internal_static_PayRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return my.suveng.istio.grpc.api.pay.Pay.internal_static_PayRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              my.suveng.istio.grpc.api.pay.PayRequest.class, my.suveng.istio.grpc.api.pay.PayRequest.Builder.class);
    }

    // Construct using my.suveng.istio.grpc.api.pay.PayRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      money_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return my.suveng.istio.grpc.api.pay.Pay.internal_static_PayRequest_descriptor;
    }

    @java.lang.Override
    public my.suveng.istio.grpc.api.pay.PayRequest getDefaultInstanceForType() {
      return my.suveng.istio.grpc.api.pay.PayRequest.getDefaultInstance();
    }

    @java.lang.Override
    public my.suveng.istio.grpc.api.pay.PayRequest build() {
      my.suveng.istio.grpc.api.pay.PayRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public my.suveng.istio.grpc.api.pay.PayRequest buildPartial() {
      my.suveng.istio.grpc.api.pay.PayRequest result = new my.suveng.istio.grpc.api.pay.PayRequest(this);
      result.money_ = money_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof my.suveng.istio.grpc.api.pay.PayRequest) {
        return mergeFrom((my.suveng.istio.grpc.api.pay.PayRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(my.suveng.istio.grpc.api.pay.PayRequest other) {
      if (other == my.suveng.istio.grpc.api.pay.PayRequest.getDefaultInstance()) return this;
      if (!other.getMoney().isEmpty()) {
        money_ = other.money_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      my.suveng.istio.grpc.api.pay.PayRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (my.suveng.istio.grpc.api.pay.PayRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object money_ = "";
    /**
     * <code>string money = 1;</code>
     * @return The money.
     */
    public java.lang.String getMoney() {
      java.lang.Object ref = money_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        money_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string money = 1;</code>
     * @return The bytes for money.
     */
    public com.google.protobuf.ByteString
        getMoneyBytes() {
      java.lang.Object ref = money_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        money_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string money = 1;</code>
     * @param value The money to set.
     * @return This builder for chaining.
     */
    public Builder setMoney(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      money_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string money = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoney() {
      
      money_ = getDefaultInstance().getMoney();
      onChanged();
      return this;
    }
    /**
     * <code>string money = 1;</code>
     * @param value The bytes for money to set.
     * @return This builder for chaining.
     */
    public Builder setMoneyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      money_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PayRequest)
  }

  // @@protoc_insertion_point(class_scope:PayRequest)
  private static final my.suveng.istio.grpc.api.pay.PayRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new my.suveng.istio.grpc.api.pay.PayRequest();
  }

  public static my.suveng.istio.grpc.api.pay.PayRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PayRequest>
      PARSER = new com.google.protobuf.AbstractParser<PayRequest>() {
    @java.lang.Override
    public PayRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PayRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PayRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PayRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public my.suveng.istio.grpc.api.pay.PayRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

