spring:
  application:
    name: istio-cloud-user-demo
  zipkin:
    base-url: http://192.168.9.208:9411
    enabled: false
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
management:
  server:
    port: 38081
server:
  port: 38080
grpc:
  server:
    port: 39090
  client:
    pay:
      address: 'static://127.0.0.1:29090' # rpc服务的地址
      negotiation-type: plaintext
    order:
      address: 'static://127.0.0.1:19090' # rpc服务的地址
      negotiation-type: plaintext
