spring:
  application:
    name: istio-cloud-user-demo
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
management:
  server:
    port: 38081
server:
  port: 38080
grpc:
  server:
    port: 39090
  client:
    pay:
      address: 'static://127.0.0.1:29090' # pay service rpc服务的地址
      negotiation-type: plaintext
    order:
      address: 'static://127.0.0.1:19090' # order service rpc服务的地址
      negotiation-type: plaintext
