spring:
  application:
    name: order
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1
  main:
    allow-bean-definition-overriding: true
management:
  server:
    port: 18081
server:
  port: 18080
grpc:
  server:
    port: 19090
  client:
    pay:
      address: 'static://127.0.0.1:29090' # pay service rpc 服务的地址
      negotiation-type: plaintext
    user:
      address: 'static://127.0.0.1:39090' # user service rpc 服务的地址
      negotiation-type: plaintext
