// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order-api.proto

package my.suveng.istio.grpc.api.order;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string pay = 1;</code>
   * @return The pay.
   */
  java.lang.String getPay();
  /**
   * <code>string pay = 1;</code>
   * @return The bytes for pay.
   */
  com.google.protobuf.ByteString
      getPayBytes();
}
