// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order-api.proto

package my.suveng.istio.grpc.api.order;

public final class Order {
  private Order() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017order-api.proto\"\033\n\014OrderRequest\022\013\n\003pay" +
      "\030\001 \001(\t\" \n\rOrderResponse\022\017\n\007orderId\030\002 \001(\t" +
      "2\221\002\n\014OrderService\0226\n\025getRealNameByUserna" +
      "me\022\r.OrderRequest\032\016.OrderResponse\022A\n\036get" +
      "RealNameByUsernameResStream\022\r.OrderReque" +
      "st\032\016.OrderResponse0\001\022A\n\036getRealNameByUse" +
      "rnameReqStream\022\r.OrderRequest\032\016.OrderRes" +
      "ponse(\001\022C\n\036getRealNameByUsernameStreamAl" +
      "l\022\r.OrderRequest\032\016.OrderResponse(\0010\001B)\n\036" +
      "my.suveng.istio.grpc.api.orderB\005OrderP\001b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "Pay", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "OrderId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
